/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashActivityRouteImport } from './routes/_dash.activity'
import { Route as DashAlertsRouteImport } from './routes/_dash.alerts'
import { Route as DashEnergyRouteImport } from './routes/_dash.energy'
import { Route as DashOverviewRouteImport } from './routes/_dash.overview'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashRoomsIndexRouteImport } from './routes/_dash.rooms.index'
import { Route as DashRoomsRoomIdRouteImport } from './routes/_dash.rooms.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashActivityRoute = DashActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashRoute,
} as any)
const DashAlertsRoute = DashAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashRoute,
} as any)
const DashEnergyRoute = DashEnergyRouteImport.update({
  id: '/energy',
  path: '/energy',
  getParentRoute: () => DashRoute,
} as any)
const DashOverviewRoute = DashOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashRoomsIndexRoute = DashRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => DashRoute,
} as any)
const DashRoomsRoomIdRoute = DashRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof DashActivityRoute
  '/alerts': typeof DashAlertsRoute
  '/energy': typeof DashEnergyRoute
  '/overview': typeof DashOverviewRoute
  '/settings': typeof DashSettingsRoute
  '/rooms/$roomId': typeof DashRoomsRoomIdRoute
  '/rooms/': typeof DashRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof DashActivityRoute
  '/alerts': typeof DashAlertsRoute
  '/energy': typeof DashEnergyRoute
  '/overview': typeof DashOverviewRoute
  '/settings': typeof DashSettingsRoute
  '/rooms/$roomId': typeof DashRoomsRoomIdRoute
  '/rooms': typeof DashRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/_dash/activity': typeof DashActivityRoute
  '/_dash/alerts': typeof DashAlertsRoute
  '/_dash/energy': typeof DashEnergyRoute
  '/_dash/overview': typeof DashOverviewRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/rooms/$roomId': typeof DashRoomsRoomIdRoute
  '/_dash/rooms/': typeof DashRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/alerts'
    | '/energy'
    | '/overview'
    | '/settings'
    | '/rooms/$roomId'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/alerts'
    | '/energy'
    | '/overview'
    | '/settings'
    | '/rooms/$roomId'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/_dash/activity'
    | '/_dash/alerts'
    | '/_dash/energy'
    | '/_dash/overview'
    | '/_dash/settings'
    | '/_dash/rooms/$roomId'
    | '/_dash/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/activity': {
      id: '/_dash/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashActivityRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/alerts': {
      id: '/_dash/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashAlertsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/energy': {
      id: '/_dash/energy'
      path: '/energy'
      fullPath: '/energy'
      preLoaderRoute: typeof DashEnergyRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/overview': {
      id: '/_dash/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof DashOverviewRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/rooms/': {
      id: '/_dash/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof DashRoomsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/rooms/$roomId': {
      id: '/_dash/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof DashRoomsRoomIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashActivityRoute: typeof DashActivityRoute
  DashAlertsRoute: typeof DashAlertsRoute
  DashEnergyRoute: typeof DashEnergyRoute
  DashOverviewRoute: typeof DashOverviewRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashRoomsRoomIdRoute: typeof DashRoomsRoomIdRoute
  DashRoomsIndexRoute: typeof DashRoomsIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivityRoute: DashActivityRoute,
  DashAlertsRoute: DashAlertsRoute,
  DashEnergyRoute: DashEnergyRoute,
  DashOverviewRoute: DashOverviewRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashRoomsRoomIdRoute: DashRoomsRoomIdRoute,
  DashRoomsIndexRoute: DashRoomsIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
